#!/usr/bin/env node
import { readFile, stat } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
const args = parseArgs(process.argv.slice(2)); if (args.help) { help(); process.exit(0) } const rootValue=String(args.root||'').trim(); if(!rootValue) fail('root is required'); const root=path.resolve(process.cwd(),rootValue); const errors=[]; const warnings=[]; const checks=[]
const check=(id,condition,message)=>{checks.push({id,ok:Boolean(condition),message}); if(!condition) errors.push(message)}; const manifest=await readJson(path.join(root,'pet.manifest.json'),'manifest'); if(!manifest) finish()
check('manifest.version',manifest.schemaVersion===1,'manifest schemaVersion must be 1'); check('manifest.species',typeof manifest.speciesId==='string'&&/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(manifest.speciesId),'speciesId must be kebab-case'); check('manifest.preset',['generic','yk-pets'].includes(manifest.preset),'preset must be generic or yk-pets')
const files=manifest.files&&typeof manifest.files==='object'?manifest.files:{}; const definition=await readText(resolveFile(files.definition),'definition'); const rig=await readText(resolveFile(files.rig),'rig'); const actions=await readText(resolveFile(files.actions),'actions'); const adapter=await readText(resolveFile(files.rendererAdapter),'renderer adapter')
requireTokens('definition',definition,['createDefault','normalize','SAFE_RANGES','symbols','chest','back','rendererIds','Number.isFinite','Math.min','Math.max','/^#[0-9a-f]{6}$/i'])
requireTokens('rig',rig,['ref="root"','ref="body"','ref="head"','ref="leftEye"','ref="rightEye"','ref="leftPupil"','ref="rightPupil"','ref="leftFrontShoulder"','ref="leftFrontForearm"','ref="leftFrontPawTip"','ref="rightFrontShoulder"','ref="rightFrontForearm"','ref="rightFrontPawTip"','ref="leftHindLeg"','ref="rightHindLeg"','name="mouthAnchor"','name="chestSymbolAnchor"','name="backSymbolAnchor"','name="propRoot"','name="sceneEffectsRoot"','motionKey','reducedMotion'])
if ((manifest.capabilities||[]).includes('segmented-tail')) requireTokens('tail rig',rig,['ref="tailRoot"','ref="tailMid"','ref="tailTip"']); check('rig.gaze',rig.includes('leftPupil.value, rightPupil.value'),'pupils should share gaze direction'); check('rig.tail-local',!/tail[^\n]{0,100}root\.value\.rotation\.y/si.test(rig),'tail motion must not rotate the whole root on Y')
requireTokens('actions',actions,['PetActionDefinition','durationMs','requiredAnchors','interruptible','idleTier','evaluate','enter','exit',"id: 'idle'", "id: 'greeting'", "id: 'jumping'"]); const ids=[...actions.matchAll(/\bid:\s*['"]([^'"]+)['"]/g)].map(m=>m[1]); check('actions.unique',new Set(ids).size===ids.length,'action IDs must be unique')
if(manifest.preset==='yk-pets') requireTokens('yk-pets adapter',adapter,['petRendererRegistry.register','createVuePetRendererAdapter','defineYkPetElement','state.recipe.appearance','state.behavior']); else requireTokens('generic adapter',adapter,['GenericRendererAdapter','createApp','supports:','mount(host','destroy()'])
await checkFile(path.join(root,'README.md'),'README'); finish()
function requireTokens(id,content,tokens){ for(const token of tokens) check(`${id}.${token}`,content.includes(token),`${id} is missing ${token}`) } function resolveFile(value){const rel=typeof value==='string'&&value.trim()?value.trim():'__missing__'; const resolved=path.resolve(root,rel); if(resolved!==root&&!resolved.startsWith(root+path.sep)){errors.push(`manifest path escapes root: ${rel}`); return path.join(root,'__invalid__')} return resolved}
async function readText(file,label){try{return await readFile(file,'utf8')}catch{errors.push(`missing ${label}: ${path.relative(process.cwd(),file)}`);return''}} async function readJson(file,label){try{return JSON.parse(await readFile(file,'utf8'))}catch(error){errors.push(`${label} is invalid: ${error instanceof Error?error.message:String(error)}`);return null}} async function checkFile(file,label){try{const info=await stat(file);check(`file.${label}`,info.isFile()&&info.size>80,`${label} is too short`)}catch{errors.push(`missing ${label}`)}}
function finish(){const report={ok:errors.length===0,errors,warnings,checks}; if(args.json) console.log(JSON.stringify(report,null,2)); else { for(const item of checks) console.log(`${item.ok?'✓':'✗'} ${item.id}`); for(const warning of warnings) console.warn(`WARN ${warning}`); if(errors.length) for(const error of errors) console.error(`ERROR ${error}`) } process.exit(errors.length?1:0)} function parseArgs(values){const out={};for(let i=0;i<values.length;i++){const value=values[i];if(value==='--help'||value==='-h'){out.help=true;continue}if(value==='--json'){out.json=true;continue}if(!value.startsWith('--'))fail(`unknown argument ${value}`);const next=values[++i];if(!next||next.startsWith('--'))fail(`${value} requires a value`);out[value.slice(2)]=next}return out} function fail(message){console.error(message);help();process.exit(1)} function help(){console.log('Usage: yk-3d-pet validate --root <pet-directory> [--json]')}
